services:
  server1:
    image: jasgo/sfc_v2:latest
    container_name: node_server_1
    ports:
      - "3000:3000"
    volumes:
      - ./V2/data:/app/data
    restart: always

  server2:
    image: jasgo/sfc_buzzer:latest
    container_name: node_server_2
    ports:
      - "3001:3001"
    restart: always

  server3:
    image: jasgo/sfc_2t1f:latest
    container_name: node_server_3
    ports:
      - "3002:3002"
    restart: always